### ISSUE TITLE
snake case for generated .rs file

### ISSUE THREAD

**Issue by OTL** [adnanademovic/genrs#1]
When we compile Hello.msg, we get Hello.rs.

When i use it in my code,

```rust
mod Hello;

use Hello::Hello; // <- error
```

I get this error.

```
error[E0255]: a module named `Hello` has already been defined in this module
 --> src/publisher.rs:4:5
  |
3 | mod Hello;
  | ---------- previous definition of `Hello` here
4 | use Hello::Hello;
  |     ^^^^^^^^^^^^ `Hello` already defined

```

How about use hello.rs for generated message?

**Comment by adnanademovic** [comment]
I'm in the process of deprecating `genrs` and moving to messages being generated at compile time. It's almost finished, and I plan on doing final steps for that over this weekend.

I'll address the bugs over there.

**Comment by OTL** [comment]
I see, thank you for quick response!
